microsoft/tfs-cli

app/app.ts, app/exec/login.ts, app/lib/auth.ts, app/lib/connection.ts, app/lib/credstore.ts, definitions/vso-node-api/vso-node-api.d.ts, package.json
- gives an error when creds are invalid (59e4eed)
- PAT tokens are accepted (c72d107)
- cred type is cached so that user doesn't have to type --authtype ___ after every command (be47572)
=> Fixed some problems with credentials

app/exec/build-tasks-upload.ts, definitions/vso-node-api/vso-node-api.d.ts, package.json
=> adjust method call to match new upload signature

app/exec/extension-create.ts, definitions/mkdirp/mkdirp.d.ts, definitions/tsd.d.ts, package.json, tsd.json
This fixes an issue in which an empty folder structure gets created in your `cwd`.
Related to Microsoft/vso-extension-tools#2.
=> Fix bad mkdirp

.gitignore, app/exec/workitem-create.ts, app/exec/workitem-query.ts, app/exec/workitem-show.ts, app/exec/workitem.ts, app/lib/arguments.ts
This PR adds workitem **show**, **query** and **create**
**show** - This takes a work item id and print out details about the work item
**query** - This lets you pass WIQL and see the results
**create** - This asks for some basic fields and then creates the work item
=> Add initial set of Work Item commands

docs/buildtasks.md
Add a note about task caching for the upload task command
=> Add note about task caching

app/exec/extension/_lib/extension-composer.ts
Add "Build and release" as a valid extension category as documented [here](https://www.visualstudio.com/en-us/integrate/extensions/develop/manifest).
=> Add "Build and release" as a valid extension category

app/exec/build/tasks/create.ts
Fixed typo in friendly name size restriction check.
=> Fixed the friendly name size restriction check.

app/exec/extension/default.ts, app/exec/extension/install.ts
Add a new tfx extension command to install an extension in a list of accounts
=> Add new tfx extension install command

app/exec/workitem/create.ts, app/exec/workitem/default.ts, app/exec/workitem/query.ts, app/exec/workitem/show.ts, app/exec/workitem/update.ts, package.json
This PR contains a few fixes / enhancements for the workitem command.
1. Added update work item command
2. Support json blob of arbitrary field values when creating/updating a work item
3. Output the fields the user chooses in query
4. Output all the fields when showing/creating/updating a work item
=> Update work items

app/exec/extension/_lib/vsix-manifest-builder.ts
=> Fixes merge of public flag by using a space-separated list

app/exec/extension/_lib/vsix-writer.ts
Fix for #99 
Read and add files to VSIX in btaches.
=> Add files to vsix in batches to avoid error EMFILE - too many open files

app/exec/build/tasks/_resources/sample.ps1, app/exec/build/tasks/create.ts
=> Revert "Update PS task sample. (not ready to merge)"

docs/buildtasks.md
"tfx build tasks delete {guid}" is wrong, should be "tfx build tasks delete --task-id {guid}"
=> Fix build task delete syntax

.vscode/launch.json, README.md, app/exec/workitem/create.ts, app/exec/workitem/query.ts, app/exec/workitem/update.ts, docs/workitems.md
1. Add docs for work item commands
2. Update validation in Update/Create to catch common errors
=> Add work items doc and add better validation in work items commands

app/exec/extension/_lib/targets/Microsoft.VisualStudio.Services/composer.ts, app/exec/extension/_lib/targets/Microsoft.VisualStudio.Services/vso-manifest-builder.ts
It is  to mandate Support link for Paid Extension during create extension
=> Changes to check for Support link in Paid Extension

app/exec/extension/_lib/interfaces.ts, app/exec/extension/_lib/publish.ts, app/exec/extension/default.ts, app/exec/extension/publish.ts
Changes for adding --no-wait-validation flag and increasing poll frequency and timeout for extension publish to support package verification workflows in marketplace
=> Changes for adding --no-wait-validation flag and increasing poll frequency for extension publish

app/exec/extension/_lib/merger.ts, app/lib/dynamicVersion.ts, docs/extensions.md
=> impl. more dynamic rev-version command

app/exec/build/tasks/create.ts, app/exec/build/tasks/default.ts, app/exec/build/tasks/delete.ts, app/exec/build/tasks/list.ts, app/exec/build/tasks/upload.ts, package-lock.json, package.json
The primary change here is to add the ability to upload an already zipped Task. This allows customers to sign a task themselves then upload directly.
The command is:
`tfx build tasks upload --task-zip-path ".\MyTask.zip"`
In this change I also:
1. Removed some unused references
1. Removed callbacks
1. Added types and const where possible
=> Add ability to upload a task zip

app/exec/extension/_lib/vsix-manifest-builder.ts, app/exec/extension/_lib/vsix-writer.ts, package-lock.json, package.json
Bug is described here: https://dev.azure.com/mseng/AzureDevOps/_workitems/edit/1769011
=> Fixed issue where additional package paths would add duplicate files

package-lock.json, package.json
Description: In the previous [PR](https://github.com/microsoft/tfs-cli/pull/410) we don't bumped the package version. This PR fixes that
=> Bump the cli version to 0.12.0

package-lock.json, package.json
=> Bump package to 0.14.0

.azure-pipelines/azure-pipeline.yml, .npmignore, package.json
- Fix npm package publishing
- Add PublishPipelineArtifact step
=> Fix azure-pipeline.yml

.azure-pipelines/azure-pipeline.yml, .npmrc, app/exec/reset.ts, app/lib/tfcommand.ts, package-lock.json, package.json
**Description**: This PR adds **.npmrc** to all packages in the repository to consume packages from the internal feed.
**Related**: [AB#2197030](https://dev.azure.com/mseng/b924d696-3eae-4116-8443-9a18392d8544/_workitems/edit/2197030)
=> Migration to CFS

app/lib/tfcommand.ts, package-lock.json, package.json
#490 
Reverting clipboardy version upgrade. This will reintroduce the cross-spawn vulnerability.
=> Revert clipboardy version

package-lock.json, package.json
TO release recent changes made via https://github.com/microsoft/tfs-cli/pull/494
=> Updating tfs-cli version for new release.

.azure-pipelines/release-pipeline.yml
Adding manual valiadation step and authenticating to npm to make sure the publish works.
=> Update release-pipeline.yml for Azure Pipelines
