microsoft/tfs-cli

- .npmignore
- app/app.ts
- app/exec/build-tasks-delete.ts
- app/exec/build-tasks-upload.ts
- app/lib/connection.ts
- app/lib/inputs.ts
- app/lib/jsonvalidate.ts
- app/lib/loader.ts
- app/lib/tfcommand.ts
- gulpfile.js
- package.json
- tests/commandline.ts
- tsconfig.json
This PR does a few improvements around the building:
* **Use [`gulp-tsb`](https://www.npmjs.com/package/gulp-tsb)**. It's simply a better approach at using TypeScript with gulp. We use it to develop VSCode.
* **Add `tsconfig.json`**. This serves both as a configuration for the compiler used in gulp, as well as a configuration for VS Code (and other tools), when editing the project. This enables dropping the nasty `/// <reference...` snippets.
* **Simplify the gulp tasks**. Instead of having multiple, interdependent tasks, just have one that does the build all at once. Gulp streams here help us out in a very nice way.
* **Fix `npm link`**. Currently it is not possible to run `npm link` because `package.json` points to `./tfx-cli.js`, which never exists at development time, since …
> Build improvements

- README.md
The login URI for extensions in the README should be https://app.market.visualstudio.com, otherwise users are still prompted for their token.
> Fix login URI in README.md for extensions

- app/exec/extension/_lib/extension-composer-factory.ts
Microsoft.VisualStudio.Services.Cloud will server as a VSSExtension target for extensions that only work for Team Services, and not for the onPrem Team Foundation Server. See https://www.visualstudio.com/en-us/integrate/extensions/develop/manifest
> Adding Microsoft.VisualStudio.Services.Cloud as VSSExtension target

- app/exec/extension/_lib/vsix-manifest-builder.ts
MIME type set in manifest was ignored on non-windows machines, this fixes that problem.
> Fixed content type override bug

- package.json
Update xml2js dependency to not use 0.4.9 to avoid being broken by xmllbuilder updates due the range version >=2.4.6 specification in xml2js 0.4.9
Start using caret ^0.4.16 for xml2js, which in turn uses a caret version for xmlbuilder.
Fic for #103
> Update xml2js dependency to not use 0.4.9

- app/exec/extension/_lib/vsix-manifest-builder.ts
This is the change to support repository property in JSON file.
Earlier we were using links property which was having "github" key along with the uri but now to maintain consistency in VSCODE and VSTS we have to planned to include another property called "repository" same like in VSCODE and after packaging the output vsixmanifest will have property referring to links to github as earlier.
Earlier JSON -
Current JSON -
Manifest -
> Changes to support repository as a separate property in extension JSON

- app/exec/extension/_lib/vsix-manifest-builder.ts
I've found that extension css files originating from .vsix files created using the current version of the `tfx` command line tool are served using an incorrect Content-Type header (`text/plain` instead of `text/css`) which results in them not being applied by most modern browsers.  It's quite frustrating.  
I made a change to the `CONTENT_TYPE_MAP` in `vsix-manifest-builder.ts` then re-built the tool, used it to generate and new .vsix for my extension and updated it and found that this *does allow `.css` files to be served with the correct `Content-Type` header allowing the stylesheet to be used.
> Use correct Content-Type header for css stylesheets

- app/exec/extension/_lib/targets/Microsoft.VisualStudio.Services/vso-manifest-builder.ts
- app/exec/extension/_lib/vsix-manifest-builder.ts
This PR updates tfx to include the showPricingCalculator property. The extension file property:
```json
"showPricingCalculator": true
````
will be translated into the vsixmanifest as:
```xml
<Property Id="Microsoft.VisualStudio.Services.Content.Pricing.PriceCalculator" Value="true"/>
```
> Add support for showPricingCalculator to vsix manifest

- app/exec/extension/_lib/vsix-manifest-builder.ts
Support a generic dictionary of following kind in the JSON manifest (vss-extension.json)
"galleryProperties": [{
"key": "value"
}]
which tfx-cli can interpret and convert to following in the VSIX manifest
<Property Id="Microsoft.VisualStudio.Services.GalleryProperties.<Key>" Value="<Value>" />
Run sanity tests.
> Adding support for custom gallery properties.

- docs/extensions.md
The old link was redirecting users here: https://www.visualstudio.com/en-us/docs/integrate/extensions/overview
Instead, users should be taken to this topic: https://www.visualstudio.com/en-us/docs/integrate/extensions/publish/command-line
> Fixing a broken link for publishing help

- app/exec/extension/_lib/extension-composer.ts
We need to support the new Azure DevOps categories. Instead of keeping the categories within the tool and the server in sync, removing the category check altogether. The server has category checks in place and those should suffice.
> Removing the category checks.

- app/exec/extension/publish.ts
- One branch was setting the temp variable and then setting it back afterwards
- The other branch could just do the single set for publishSettings.vsixPath
> Remove intermediary createdExtensionVsixPath var

- .npmignore
I thought this was done automatically for `.` folders, but noticed it in my node_modules
> chore: Ignore .vscode from NPM

- package.json
Fix requiring NodeJS 8 or later, as per intent of https://github.com/Microsoft/tfs-cli/commit/11745aa9a0d4790f23892a59141b40a02fa8f209 /cc @trevorsg 
Fixes https://github.com/Microsoft/tfs-cli/issues/288
> Fix engines/node in package.json for NodeJS 8+

- app/lib/jsonvalidate.ts
Fixes #297 by updating tfx's validation of the task name to use the same regex as the task manifest schema (`/^[A-Za-z0-9\-]+$/`)
* Task schema for name https://github.com/Microsoft/azure-pipelines-task-lib/blob/master/tasks.schema.json#L16
* tfx jsonvalidate is using the `isAlphanumeric` function from the validator library here: https://github.com/Microsoft/tfs-cli/blob/master/app/lib/jsonvalidate.ts#L68
* source for the `isAlphanumeric` function https://github.com/chriso/validator.js/blob/master/validator.js#L866
> Fix Task Name Validation

- app/exec/build/tasks/upload.ts
- package-lock.json
- package.json
There was a bug in this code when uploading a task zip. We were processing the zip to get some file contents then recreating the stream. Instead, we should preserve the original file stream so that we don't break signing.
> Fix uploading task zip to preserve original file stream

- app/exec/extension/_lib/publish.ts
- package-lock.json
- package.json
Updating to the latest REST API version.
The 5.1 preview 2 version is resulting in the wrong controller receiving the extension publish request. Updating to the latest 6.1 preview 2 version for Azure DevOps Server 2020.
This change was tested against 2020 and 2019, and works against both.
> Fix REST API version for hard coded extension APIs

- app/exec/extension/_lib/merger.ts
Addressing the --rev-version bug in #358.
The json-in-place set function returns an Inplace type object, which was causing issues. This adds a toString so that it can be properly written back to the json file.
> Fix --rev-version bug

- app/exec/extension/init.ts
This PR implements the fix suggested in [issue 363](https://github.com/microsoft/tfs-cli/issues/363).
Currently `tfx extension init` is broken for anyone on a non Windows system. 
The code in this PR now checks for both `\` and `/` when checking a file path, instead of just checking what Windows uses, `\`.
> Fix extension init command for non Windows users

- app/exec/extension/_lib/interfaces.ts
- app/exec/extension/_lib/merger.ts
- app/exec/extension/create.ts
- app/exec/extension/default.ts
- app/exec/extension/init.ts
- app/exec/extension/publish.ts
- app/exec/extension/resources/create.ts
- docs/extensions.md
This PR adds support for webpack-like configuration of the manifest file by giving the option to provide a manifest js file instead of a manifest json file.
From the updated documentation:
"Use the `--manifest-js` option to supply a Node.JS CommonJS module and export a function. The function will be invoked with an environment property bag as a parameter, and must return the manifest JSON object.  Environment variables for the property bag are specified with the `--env` command line parameter.  These are space separated key-value pairs, e.g. `--env mode=production rootpath="c:\program files" size=large`."
This can address scenarios described by the following issues.  Fixes #92, Fixes #161, Fixes #258.
An example manifest JS file might look like the following.  It's inspired by David …
> Allow flexible manifest specification, including production vs. development differences

- app/exec/extension/default.ts
[This change](https://github.com/microsoft/tfs-cli/pull/342#discussion_r603296197) of manifestJs from args.StringArgument to args.ReadableFilePathsArgument created a bug that causes the parser to fail when --manifest-js was specified.
> Fix cmd line parsing bug for the --manifest-js parameter

- app/exec/extension/_lib/interfaces.ts
- app/exec/extension/_lib/merger.ts
- app/exec/extension/default.ts
- docs/extensions.md
There are valid scenarios where you may want to use both --manifest-js and --override or --overrides-file.  For example, in ADO pipeline publishing to update the extension version with the build version from the pipeline.
In fact, the internal implementation of --publisher and --extension-id also depend on this override functionality.  This PR will allow them to be used with --manifest-js.
This PR is in response to a comment from PR #342 by @dwilsonactual.
> Restore the use of --override and --overrides-file when --manifest-js is specified

- app/exec/extension/_lib/loc.ts
- app/exec/extension/_lib/vsix-writer.ts
- app/exec/extension/init.ts
- app/lib/jsonvalidate.ts
- package-lock.json
- package.json
Updated dependencies:
- `mkdirp` to 1.0.4 - after this update `mkdirp` function changed: now it uses a promise instead of a callback. Had to make some code changes to fix that.
- `shelljs` to 0.8.5
- `validator` to 13.7.0
List of commands tested locally:
- login
- workitem create
- workitem query
- workitem update
- workitem show
- build list
- build queue
- build show
- build tasks create
- build tasks upload
- build tasks list
- build tasks delete
- extension create
> Resolve vulnerabilities

- .vscode/tasks.json
**Description**: VSCode task ver 0.1.0 is deprecated at the moment.
Auto-upgraded task to ver. 2.0.0
> Upgrade task.json to the new version

- README.md
- app/exec/login.ts
- app/lib/tfcommand.ts
- package-lock.json
- package.json
**Description**: added new parameter `--skipCertValidation` (`--skip-cert-validation`) to group `Global server command argument` which allows to skip certificate validation during login
**Related issue:** https://github.com/microsoft/tfs-cli/issues/419
```bash
~ tfx login
TFS Cross Platform Command Line Interface v0.13.0
Copyright Microsoft Corporation
> Service URL: https://some-url
> Personal access token:
error: Error: Connection failed. Check your internet connection & collection URL.
error: Message: unable to get local issuer certificate
~ tfx login --skip-cert-validation
TFS Cross Platform Command Line Interface v0.13.0
Copyright Microsoft Corporation
> Service URL: https://some-url
> Personal access token:                                           
Logged in successfully
```
> Added new parameter skipCertValidation

- app/lib/jsonvalidate.ts
**Description**: Some node runners go to EOL. We need to notify authors if there are only deprecated runners. 
**How it works**: While uploading task to Azure Devops, validation checks the execution handlers in task.json file. If there is not any runner rather than deprecated ones, warning will appear. 
Warning looks like:
> Added deprecated runner validation

- package.json
**Description**:
Since `0.15.0` was already published to npmjs registry, this PR bumps package version to 0.16.0
> Bump tfs-cli tool version to 0.16.0

- .azure-pipelines/azure-pipeline.yml
fixes [CodeQL error ](https://dev.azure.com/mseng/PipelineTools/_build/results?buildId=26850245&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=4bb9ee66-d15b-54bf-dea1-47f4e6298783&l=62)
**Description**
- Added node16 installation for CodeQL 3000, because the task requires node 14+ and the default node version after pipeline run sets to 10.x
**Testing**
> CodeQL 3000 fix

- app/lib/jsonvalidate.ts
- package-lock.json
- package.json
**WI**: [AB#2122131](https://dev.azure.com/mseng/b924d696-3eae-4116-8443-9a18392d8544/_workitems/edit/2122131)
**Description**
Added `Node10` and `Node16` to the list of deprecated runners, as their respective Node versions reached the EoL.
**Tests**
When there is at least one runner in `task.json` that is not deprecated (i.e. Node20_1), no warning is displayed on task upload:
When all runners in  `task.json` are deprecated, this warning is displayed:
> Update the list of deprecated runners

- .devcontainer/devcontainer.json
- .editorconfig
VSCode DevContainers (https://code.visualstudio.com/docs/devcontainers/containers) helps developers to have the same development infrastructure, like;
- Same editor settings
- Same VSCode extensions
- Same tools installed to the system
So, when the project opened in VSCode, same tools with the same configurations are ready to use
This will remove the differences between the development environments of the developers
> creating initial devcontainer configuration

- app/exec/build/tasks/upload.ts
- app/exec/extension/_lib/merger.ts
- app/lib/jsonvalidate.ts
- package-lock.json
- package.json
**WI**
[AB#2221223](https://dev.azure.com/mseng/b924d696-3eae-4116-8443-9a18392d8544/_workitems/edit/2221223)
**Description**
This pull request adds the `task.json` validation for the `tfx extension create` command. If the file does not adhere to the [schema](https://raw.githubusercontent.com/Microsoft/azure-pipelines-task-lib/master/tasks.schema.json), the command will output a warning message.
**Examples**
- When the task name in `task.json` contains a wrong symbol:
- When there are no validation errors, no warnings are displayed:
> Implemented `task.json` validation for `tfx extension create` command

- app/lib/tfcommand.ts
- package-lock.json
- package.json
Upgrades clipboardy to 4.0.0 which has long patched the cross-spawn vulnerability.
> Upgrade clipboardy to patch vulnerability in cross-spawn

- app/exec/extension/_lib/interfaces.ts
- app/exec/extension/_lib/publish.ts
- app/exec/extension/default.ts
- app/exec/extension/publish.ts
- app/exec/extension/resources/create.ts
- app/exec/extension/share.ts
Enables using tfx to publish an extension that has increased scopes compared to the published version.
Stracked on top of #458.
> Plumb through bypassScopeCheck

- .azure-pipelines/azure-pipeline.yml
- .azure-pipelines/common-steps.yml
- .azure-pipelines/release-pipeline.yml
Splitting CI and release pipeline for this tool to make sure we can generate the package for testing via CI pipeline and check the package before uploading to npm.
> Splitting CI and release pipeline for this tool 

- .azure-pipelines/release-pipeline.yml
The npm package will be releases with prerelease tag initially. once the proper testing is done then we can run the additional manual stage to make it latest. this way we can catch any regressions in prerelease. 
Test Run : Have tested these changes in private org with dummy npm package.
> Seperating the release process into prerelease and release 

- app/lib/jsonvalidate.ts
- package.json
Improve clarity and consistency in the validation of execution handlers while updating the version.
This pull request refactors and improves the validation logic for task execution handlers in `app/lib/jsonvalidate.ts`, ensuring more robust and comprehensive validation across different execution types. It also bumps the package version in `package.json` to reflect these changes.
* Refactored execution handler validation by introducing the `validateAllExecutionHandlers` and `validateExecutionTarget` helper functions, allowing validation of `execution`, `prejobexecution`, and `postjobexecution` blocks uniformly.
* Ensured that the validation function always returns an array of issues, even when the execution block is missing, preventing undefined return values for tasks without execution …
> Refactor execution handler validation and version bump
